DROP TABLE IF EXISTS AlbumSongs;
DROP TABLE IF EXISTS PlaylistSongs;
DROP TABLE IF EXISTS ListenHistory;
DROP TABLE IF EXISTS AlbumRatings;
DROP TABLE IF EXISTS SongRatings;
DROP TABLE IF EXISTS Follows;
DROP TABLE IF EXISTS Songs;
DROP TABLE IF EXISTS Playlists;
DROP TABLE IF EXISTS Albums;
DROP TABLE IF EXISTS Genres;
DROP TABLE IF EXISTS Artists;
DROP TABLE IF EXISTS Admins;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
	u_UserID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	u_Username VARCHAR(30) UNIQUE NOT NULL,
	u_PasswordHash VARCHAR(255) NOT NULL,
	u_FirstName VARCHAR(50) NOT NULL,
u_LastName VARCHAR(50) NOT NULL, 
	u_Email VARCHAR(255) UNIQUE NOT NULL,

	CHECK (u_Username ~ '^[A-Za-z0-9_ ]+$')
);

CREATE TABLE Admins (
	a_AdminID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	a_UserID INT UNIQUE NOT NULL,

	FOREIGN KEY (a_UserID) REFERENCES Users(u_UserID) ON DELETE CASCADE
);

CREATE TABLE Artists (
	art_ArtistID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	art_UserID INT UNIQUE NOT NULL,

	FOREIGN KEY (art_UserID) REFERENCES Users(u_UserID) ON DELETE CASCADE
);

CREATE TABLE Genres (
	g_GenreID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	g_Name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Albums (
	al_AlbumID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	al_ReleaseDate DATE,
	al_ArtistID INT NOT NULL,
	al_GenreID INT NOT NULL,
	al_Name VARCHAR(150) NOT NULL,

	FOREIGN KEY (al_ArtistID) REFERENCES Artists(art_ArtistID),
FOREIGN KEY (al_GenreID) REFERENCES Genres(g_GenreID)
);

CREATE TABLE Playlists (
	pl_PlaylistID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	pl_Name VARCHAR(150) NOT NULL,
	pl_CreatedAt DATE NOT NULL,
pl_UserID INT NOT NULL,

	FOREIGN KEY (pl_UserID) REFERENCES Users(u_UserID) ON DELETE CASCADE
);

CREATE TABLE Songs (
	s_SongID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	s_Name VARCHAR(150) NOT NULL,
	s_Length INT NOT NULL,
	s_ReleaseDate DATE NOT NULL,
	s_ArtistID INT,
	s_GenreID INT,

	FOREIGN KEY (s_ArtistID) REFERENCES Artists(art_ArtistID),
	FOREIGN KEY (s_GenreID) REFERENCES Genres(g_GenreID)
);

CREATE TABLE Follows (
	f_FollowerID INT NOT NULL,
	f_FollowedID INT NOT NULL,
	f_CreatedAt DATE,

	PRIMARY KEY (f_FollowerID, f_FollowedID),
	FOREIGN KEY (f_FollowerID) REFERENCES Users(u_UserID) ON DELETE CASCADE,
FOREIGN KEY (f_FollowedID) REFERENCES Users(u_UserID) ON DELETE CASCADE
);

CREATE TABLE SongRatings (
	sr_Rating INT NOT NULL,
	sr_CreateDate DATE NOT NULL,
	sr_UserID INT NOT NULL,
	sr_SongID INT NOT NULL,

	PRIMARY KEY (sr_UserID, sr_SongID),
	FOREIGN KEY (sr_UserID) REFERENCES Users(u_UserID) ON DELETE CASCADE,
	FOREIGN KEY (sr_SongID) REFERENCES Songs(s_SongID) ON DELETE CASCADE
);

CREATE TABLE AlbumRatings (
ar_Rating INT NOT NULL,
	ar_CreateDate DATE NOT NULL,
	ar_UserID INT NOT NULL,
	ar_AlbumID INT NOT NULL,

	PRIMARY KEY (ar_UserID, ar_AlbumID),
	FOREIGN KEY (ar_UserID) REFERENCES Users(u_UserID) ON DELETE CASCADE,
	FOREIGN KEY (ar_AlbumID) REFERENCES Albums(al_AlbumID) ON DELETE CASCADE
);

CREATE TABLE ListenHistory (
	lr_HistoryID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	lr_ListenedTime INT NOT NULL,
	lr_UserID INT NOT NULL,
	lr_SongID INT NOT NULL,

	UNIQUE (lr_UserID, lr_SongID),
	FOREIGN KEY (lr_UserID) REFERENCES Users(u_UserID) ON DELETE CASCADE,
	FOREIGN KEY (lr_SongID) REFERENCES Songs(s_SongID) ON DELETE CASCADE
);

CREATE TABLE AlbumSongs (
	als_AlbumID INT NOT NULL,
	als_SongID INT NOT NULL,

	PRIMARY KEY (als_AlbumID, als_SongID),
	FOREIGN KEY (als_AlbumID) REFERENCES Albums(al_AlbumID) ON DELETE CASCADE,
	FOREIGN KEY (als_SongID) REFERENCES Songs(s_SongID) ON DELETE CASCADE
);

CREATE TABLE PlaylistSongs (
	ps_PlaylistID INT NOT NULL,
	ps_SongID INT NOT NULL,

	PRIMARY KEY (ps_PlaylistID, ps_SongID),
	FOREIGN KEY (ps_PlaylistID) REFERENCES Playlists(pl_PlaylistID) ON DELETE CASCADE,
	FOREIGN KEY (ps_SongID) REFERENCES Songs(s_SongID) ON DELETE CASCADE
);
